/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FindProviderForm: typeof import('./components/patients/form/FindProviderForm.vue')['default']
    FindProviderFormQuestion: typeof import('./components/patients/form/FindProviderFormQuestion.vue')['default']
    FindProviderFormResponse: typeof import('./components/patients/form/FindProviderFormResponse.vue')['default']
    GlobalFooter: typeof import('./components/global/GlobalFooter.vue')['default']
    GlobalNav: typeof import('./components/global/GlobalNav.vue')['default']
    GoogleMapsProviderCell: typeof import('./components/patients/providers/GoogleMapsProviderCell.vue')['default']
    MultiStepForm: typeof import('./components/patients/form/MultiStepForm.vue')['default']
    ProviderCell: typeof import('./components/patients/providers/ProviderCell.vue')['default']
    ProviderMap: typeof import('./components/patients/providers/ProviderMap.vue')['default']
    Questionnaire: typeof import('./components/questionnaire/index.vue')['default']
    QuestionnaireContainer: typeof import('./components/questionnaire/QuestionnaireContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VerifiedProviderCell: typeof import('./components/patients/providers/VerifiedProviderCell.vue')['default']
  }
}
